branches:
  only:
    - gh-pages
if: commit_message == "Trigger build"
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 'lts/*'
before_install:
  - git pull
  - git submodule update --init --recursive
install:
  - npm install
script:
  - npm run update pages docs 20 2000
  - npm run fullbuild indices docs
after_success:
  - git config user.email "travis@travis.org"
  - git config user.name "travis"
  - git add .
  - git commit --allow-empty -m "Update mirror"
  - git push https://Lee0701:${APP_PASSWORD}@${REPO_REF} HEAD:gh-pages