
name: Trigger build

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Make POST request
        env:
          BODY: "{\"request\":{\"branch\":\"gh-pages\",\"message\":\"Trigger build\"}}"
        run: |
          curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "Accept: application/json" \
          -H "Travis-API-Version: 3" \
          -H "Authorization: token ${{ secrets.TOKEN }}" \
          -d "$BODY" \
          https://api.travis-ci.com/repo/hanja-club%2Fkiwi/requests
