name: trigger-update

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  trigger-update:
    runs-on: ubuntu-latest

    steps:
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: gh-pages
        commit_options: '--allow-empty'
        commit_message: Trigger build
