name: trigger-update

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  trigger-update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_options: '--allow-empty'
        commit_message: Trigger build
