
name: trigger-build

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: gh-pages
        commit_options: '--allow-empty'
        commit_message: Trigger build
